apiVersion: v1
kind: Service
metadata:
    name: "demoaksculster009-fc8d"
    labels:
        app: "demoaksculster009-fc8d"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "demoaksculster009-fc8d"