on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: demoacr009.azurecr.io
        username: ${{ secrets.acr_demoacr009_username }}
        password: ${{ secrets.acr_demoacr009_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t demoacr009.azurecr.io/demoaksculster009:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push demoacr009.azurecr.io/demoaksculster009:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_demoaksculster009_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep demoaksculster009bd29 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace demoaksculster009bd29`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: demoaksculster009bd29
        container-registry-url: demoacr009.azurecr.io
        container-registry-username: ${{ secrets.acr_demoacr009_username }}
        container-registry-password: ${{ secrets.acr_demoacr009_password }}
        secret-name: demoaksculstdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: demoaksculster009bd29
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          demoacr009.azurecr.io/demoaksculster009:${{ github.sha }}
        imagepullsecrets: |
          demoaksculstdockerauth
